// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_REST.Models
{
    public partial class Generos
    {
        public Generos()
        {
            Peliculas = new HashSet<Peliculas>();
        }

        public int Id { get; set; }
        public string Descripcion { get; set; }

        public virtual ICollection<Peliculas> Peliculas { get; set; }
    }
}