// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_REST.Models
{
    public partial class Usuarios
    {
        public Usuarios()
        {
            Peliculas = new HashSet<Peliculas>();
        }

        public int Id { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }

        public virtual ICollection<Peliculas> Peliculas { get; set; }
    }
}